services:

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    restart: unless-stopped
    env_file:
      - .env

  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - text_service
      - ai_service
      - session_service
    restart: unless-stopped

  text_service:
    build: ./backend/text_service
    image: text_service
    container_name: text
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --root-path /text
    depends_on:
      - redis
      - minio
    ports:
      - "127.0.0.1:8005:8000"
    restart: unless-stopped
    env_file:
      - .env

  cleanup_service:
    build: ./backend/cleanup_service/textshare-cleanup-service
    image: cleanup_service
    container_name: cleanup
    depends_on:
      - redis
      - minio
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env

  session_service:
    build: ./backend/session_service
    image: session_service
    container_name: session
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --root-path /session
    depends_on:
      - redis
    ports:
      - "127.0.0.1:8003:8000"
    restart: unless-stopped
    env_file:
      - .env

  ai_service:
    build: ./backend/ai_service
    image: ai_service
    container_name: ai
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --root-path /ai
    depends_on:
      - redis
    ports:
      - "127.0.0.1:8006:8000"
    restart: unless-stopped
    env_file:
      - .env

volumes:
  redis_data:
  minio_data:
